id: AE6619778
title: f432E
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - de
  datatype: PlainText
  created_at: 2022-05-27 20:25:07.967855
  last_modified_at: 2022-05-27 20:25:07.967858
