id: AE6619778
title: f6627
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - de
  datatype: PlainText
  created_at: 2022-05-27 20:25:07.982131
  last_modified_at: 2022-05-27 20:25:07.982133
