id: AE6619778
title: f7257
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - de
  datatype: PlainText
  created_at: 2022-05-27 20:25:07.987773
  last_modified_at: 2022-05-27 20:25:07.987777
