id: AE6619778
title: fCC1C
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - de
  datatype: PlainText
  created_at: 2022-05-27 20:25:08.040802
  last_modified_at: 2022-05-27 20:25:08.040805
